export const LOAD_NEWS = 'LOAD_NEWS';
export const LOGIN_SERVICE_LOADING = 'LOGIN_SERVICE_LOADING';
export const LOGIN_SERVICE_ERROR = 'LOGIN_SERVICE_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const RESET_LOGIN_ERROR_MESSAGE = 'RESET_LOGIN_ERROR_MESSAGE';
export const ENABLE_LOGIN_SUCCESS = 'ENABLE_LOGIN_SUCCESS';
